/**
 * ffmpeg argument builders: each element is one argv entry, passed to
 * spawn WITHOUT a shell, so paths with spaces or shell metacharacters
 * are safe. values copied from the previously shell-interpolated
 * command strings (except the live bufsize arithmetic, now computed).
 */

const THREE_VARIANT_FILTER =
	'[0:v]fps=fps=30,split=3[v1][v2][v3];[v1]scale=width=-2:height=1080[1080p];[v2]scale=width=-2:height=720[720p];[v3]scale=width=-2:height=360[360p]';
const THREE_VARIANT_STREAM_MAP = 'v:0,a:0,name:1080p v:1,a:1,name:720p v:2,a:2,name:360p';

export function buildVodArgs(input: string, threads: number): string[] {
	return [
		'-hide_banner',
		'-loglevel',
		'info',
		'-y',
		'-threads',
		String(threads),
		'-i',
		input,
		'-codec:v',
		'libx264',
		'-crf:v',
		'23',
		'-profile:v',
		'high',
		'-pix_fmt:v',
		'yuv420p',
		'-rc-lookahead:v',
		'40',
		'-force_key_frames:v',
		'expr:gte(t,n_forced*2.000)',
		'-preset:v',
		'veryfast',
		'-b-pyramid:v',
		'strict',
		'-filter_complex',
		THREE_VARIANT_FILTER,
		'-map',
		'[1080p]',
		'-maxrate:v:0',
		'2500000',
		'-bufsize:v:0',
		'5000000',
		'-level:v:0',
		'4.0',
		'-map',
		'[720p]',
		'-maxrate:v:1',
		'1700000',
		'-bufsize:v:1',
		'3200000',
		'-level:v:1',
		'3.1',
		'-map',
		'[360p]',
		'-maxrate:v:2',
		'800000',
		'-bufsize:v:2',
		'1600000',
		'-level:v:2',
		'3.1',
		'-codec:a',
		'aac',
		'-ar',
		'44100',
		'-ac:a',
		'2',
		'-map',
		'0:a:0',
		'-b:a:0',
		'192000',
		'-map',
		'0:a:0',
		'-b:a:1',
		'128000',
		'-map',
		'0:a:0',
		'-b:a:2',
		'96000',
		'-f',
		'hls',
		'-hls_flags',
		'+independent_segments+program_date_time+single_file',
		'-hls_time',
		'6',
		'-hls_playlist_type',
		'vod',
		'-hls_segment_type',
		'mpegts',
		'-master_pl_name',
		'master.m3u8',
		'-var_stream_map',
		THREE_VARIANT_STREAM_MAP,
		'-hls_segment_filename',
		'segment_%v.ts',
		'manifest_%v.m3u8',
	];
}

export function buildSubtitleArgs(
	videoInput: string,
	subtitleInput: string,
	langCode: string,
	threads: number,
): string[] {
	return [
		'-hide_banner',
		'-threads',
		String(threads),
		'-loglevel',
		'info',
		'-y',
		'-i',
		videoInput,
		'-i',
		subtitleInput,
		'-c:v',
		'copy',
		'-c:s',
		'webvtt',
		'-map',
		'0:v',
		'-map',
		'1:s',
		'-f',
		'hls',
		'-hls_time',
		'6',
		'-hls_playlist_type',
		'vod',
		'-hls_subtitle_path',
		'sub_vtt_%v.m3u8',
		'-hls_segment_type',
		'mpegts',
		'-var_stream_map',
		`v:0,s:0,name:${langCode},sgroup:subtitle`,
		'-hls_segment_filename',
		'redundant_%v_%04d.ts',
		'sub_vtt_%v.m3u8',
	];
}

export function buildLiveArgs(rtmpInput: string, threads: number): string[] {
	return [
		'-hide_banner',
		'-loglevel',
		'info',
		'-y',
		'-threads',
		String(threads),
		// bound a stalled rtmp source: exit if no data arrives for 30s
		// (srs can leave pull connections hanging after unpublish)
		'-rw_timeout',
		String(30_000_000),
		'-i',
		rtmpInput,
		'-filter_complex',
		THREE_VARIANT_FILTER,
		'-codec:v',
		'libx264',
		'-crf:v',
		'23',
		'-tune',
		'zerolatency',
		'-pix_fmt:v',
		'yuv420p',
		'-rc-lookahead:v',
		'60',
		'-force_key_frames:v',
		'expr:gte(t,n_forced*2.000)',
		'-preset:v',
		'fast',
		'-b-pyramid:v',
		'strict',
		'-map',
		'[1080p]',
		'-maxrate:v:0',
		'2000000',
		'-bufsize:v:0',
		String(2 * 2000000),
		'-level:v:0',
		'4.0',
		'-map',
		'[720p]',
		'-maxrate:v:1',
		'1200000',
		'-bufsize:v:1',
		String(2 * 1000000),
		'-level:v:1',
		'3.1',
		'-map',
		'[360p]',
		'-maxrate:v:2',
		'700000',
		'-bufsize:v:2',
		String(2 * 500000),
		'-level:v:2',
		'3.1',
		'-codec:a',
		'aac',
		'-ac:a',
		'2',
		'-map',
		'0:a:0',
		'-b:a:0',
		'192000',
		'-map',
		'0:a:0',
		'-b:a:1',
		'128000',
		'-map',
		'0:a:0',
		'-b:a:2',
		'96000',
		'-f',
		'hls',
		'-hls_flags',
		'+independent_segments',
		'-hls_time',
		'6',
		'-hls_playlist_type',
		'event',
		'-hls_segment_type',
		'mpegts',
		'-master_pl_name',
		'master.m3u8',
		'-var_stream_map',
		THREE_VARIANT_STREAM_MAP,
		'-hls_segment_filename',
		'segment_%v_%05d.ts',
		'manifest_%v.m3u8',
	];
}
